[logger]
    name = ""                                                           # имя логгера
    levels = ["fatal","info","error","warn","debug","trace"]            # уровни логирования
    [logger.bindings]                                                   # дополнительные ключи
        key1 = "key1-val"
        key2 = "key2-val"
    [logger.output]                                                     # настройка отображения
        timestamp = "full"                                              # вывод времени full, short, unix и none
        levels = ["fatal","info","error","warn","debug","trace"]        # вывод типов
        bindings = "bracket"                                            # отображение ключей square, bracket, none, no-wrapper

[api]
    enable = false              # активация API сервера
    logging = false             # логирование запросов
    hostname = "0.0.0.0"        # хост          
    port = 3001                 # порт
    backlog = 511               # очередь баклога
    prefix = "/api"             # префикс
    connection_timeout = 0      # таймаут сервера в милисекундах
    keep_alive_timeout = 5000   # таймаут keep-alive сервера в милисекундах
    body_limit = 1048576        # максимальный размер тела запроса в байтах
    trust_proxy = false         # доверие proxy закголовку